# Generated by Django 5.2.1 on 2025-05-31 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staydine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='total_rooms',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
