# Generated by Django 5.2.1 on 2025-06-09 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staydine', '0002_roomtype_total_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='dining',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dining',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
