# Generated by Django 5.2.1 on 2025-06-09 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staydine', '0003_dining_id_alter_dining_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accommodation',
            name='bed_type',
        ),
        migrations.RemoveField(
            model_name='accommodation',
            name='room',
        ),
        migrations.AddField(
            model_name='accommodation',
            name='classic_rooms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='premium_rooms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='suite_rooms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
